trigger:
  branches:
    include:
      - main
  paths:
    include:
      - workflows/**  # Trigger pipeline only when files change in workflows directory

variables:
  azureSubscription: 'Logic-app-connection'  # Azure DevOps Service Connection
  resourceGroupName: 'CustomAppsIntServices'
  azureRegion: 'South India'

stages:
  - stage: Deploy_LogicApps
    displayName: "Deploy Logic Apps Workflows"
    jobs:
      - job: Deploy_Workflows
        displayName: "Deploy Changed Logic Apps"
        pool:
          vmImage: 'ubuntu-latest'  # Run on Ubuntu latest agent

        steps:
          # Step 1: Checkout the repository
          - checkout: self
            displayName: "Checkout Source Code"

          # Step 2: Identify changed files in the workflows directory
          - script: |
              echo "Identifying changed workflow files..."
              git fetch origin main
              CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '^workflows/.*\.json$' || true)
              
              # Convert list of files to a comma-separated string for further use
              echo "Changed files: $CHANGED_FILES"
              echo "##vso[task.setvariable variable=changedFiles;]$CHANGED_FILES"
            displayName: "Identify Changed Workflow Files"
            
           # Step 3: Azure CLI Login
          - task: AzureCLI@2
            displayName: "Azure CLI Login"
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Azure Login Successful."


          # Step 4: Deploy Logic Apps for each changed file
          - task: AzureCLI@2
            displayName: "Deploy Logic App Templates"
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                CHANGED_FILES="$(changedFiles)"
                if [ -z "$CHANGED_FILES" ]; then
                  echo "No changed files to deploy."
                  exit 0
                fi

                for file in $CHANGED_FILES; do
                  echo "Deploying Logic App for file: $file"
                  WORKFLOW_NAME=$(basename "$file" .json)
                  az deployment group create \
                    --resource-group $(resourceGroupName) \
                    --template-file "$file" \
                    --parameters logicAppName=$WORKFLOW_NAME location=$(azureRegion)
                  echo "Deployment for $WORKFLOW_NAME completed."
                done


               
