trigger:
  branches:
    include:
      - main
  paths:
    include:
      - workflows/**  # Trigger pipeline only when files change in workflows directory

variables:
  azureSubscription: 'Logic-app-connection'  # Azure DevOps Service Connection
  resourceGroupName: 'CustomAppsIntServices'
  azureRegion: 'South India'

stages:
  - stage: Deploy_LogicApps
    displayName: "Deploy Logic Apps Workflows"
    jobs:
      - job: Deploy_Workflows
        displayName: "Deploy Changed Logic Apps"
        pool:
          vmImage: 'ubuntu-latest'  # Run on Ubuntu latest agent

        steps:
          # Step 1: Checkout the repository
          - checkout: self
            displayName: "Checkout Source Code"
            fetchDepth: 0  # Fetch full Git history

          # Step 2: Identify changed files in the workflows directory
          - script: |
              echo "Identifying changed workflow files..."
              git fetch origin main  # Ensure the latest branch state is fetched
              CHANGED_FILES=$(
