trigger:
  branches:
    include:
      - main
  paths:
    include:
      - workflows/**  # Trigger pipeline only when files change in workflows directory

variables:
  azureSubscription: 'Logic-app-connection'  # Azure DevOps Service Connection
  resourceGroupName: 'CustomAppsIntServices'
  azureRegion: 'South India'

stages:
  - stage: Deploy_LogicApps
    displayName: "Deploy Logic Apps Workflows"
    jobs:
      - job: Deploy_Workflows
        displayName: "Deploy Changed Logic Apps"
        pool:
          vmImage: 'ubuntu-latest'  # Run on Ubuntu latest agent

        steps:
          # Step 1: Checkout the repository
          - checkout: self
            displayName: "Checkout Source Code"
            fetchDepth: 0  # Fetch full Git history

          # Step 2: Identify changed files
          - script: |
              # Ensure we have the full commit history
              git fetch --unshallow || true

              # Check if the previous commit exists
              if git rev-parse HEAD^ >/dev/null 2>&1; then
                echo "Not the initial commit"
                # Compare the current commit with the previous commit to find changed files
                changed_files=$(git diff --name-only HEAD^ HEAD | grep '^workflows/.*\.json$' || true)
              else
                echo "Initial commit detected"
                # For the initial commit, list all files in the workflows directory
                changed_files=$(git ls-files workflows/*.json || true)
              fi
              echo "Changed files: $changed_files"
              # Set the changed files as a pipeline variable
              echo "##vso[task.setvariable variable=changedFiles;]$changed_files"
            displayName: "Identify Changed Workflow Files"

          # Step 3: Azure CLI Login
          - task: AzureCLI@2
            displayName: "Azure CLI Login"
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Azure Login Successful."

          # Step 4: Deploy Logic Apps for each changed file
          - task: AzureCLI@2
            displayName: "Deploy Logic App Templates"
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                CHANGED_FILES="$(changedFiles)"
                if [ -z "$CHANGED_FILES" ]; then
                  echo "No changed files to deploy."
                  exit 0
                fi

                for file in $CHANGED_FILES; do
                  echo "Deploying Logic App for file: $file"
                  WORKFLOW_NAME=$(basename "$file" .json)
                  az deployment group create \
                    --resource-group $(resourceGroupName) \
                    --template-file "$file" \
                    --parameters logicAppName=$WORKFLOW_NAME location=$(azureRegion)
                  echo "Deployment for $WORKFLOW_NAME completed."
                done
