name: Push to Approved Code Repo

on:
  push:
    branches:
      - main

jobs:
  push-to-repo2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 1
        uses: actions/checkout@v3
        with:
          repository: PawarSavitha/Logicapp-workflow 
          ref: main

      - name: Push to Approved Code Repository
        env:
          REPO2_PAT: ${{ secrets.REPO2_PAT }}  
        run: |
          git clone https://$REPO2_PAT@github.com/PawarSavitha/approved-code-repo.git Final-Logic-app-code

          cp -r * Final-Logic-app-code/

          cd Final-Logic-app-code

         
          git config user.name "PawarSavitha"
          git config user.email "savithapawar038@gmail.com"

          git add .
          git commit -m "Approved logic app code"
          git push origin main
