name: Push to Approved Code Repo

on:
  push:
    branches:
      - main

jobs:
  push-to-repo2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 1
        uses: actions/checkout@v3
        with:
          repository: your-org/development-repo
          ref: main

      - name: Push to Approved Code Repository
        run: |
          	 git clone https://github.com/PawarSavitha/Logicapp-workflow Final-Logic-app-code
          	 cp -r * Final-Logic-app-code/
          	 cd Final-Logic-app-code
          	 git config PawarSavitha "GitHub Action"
          	 git config savithapawar038@gmail.com l "action@github.com"
          	 git add .
          	 git commit -m "Approved logic app code"
          	 git push origin main
