name: Push to Approved Code Repo

on:
  push:
    branches:
      - main

jobs:
  push-to-repo2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 1
        uses: actions/checkout@v3
        with:
          repository: PawarSavitha/Logicapp-workflow  # Make sure to replace this with the correct repository
          ref: main

      - name: Push to Approved Code Repository
        env:
          REPO2_PAT: ${{ secrets.REPO2_PAT }}  # Make sure you set up the secret in Repository 1
        run: |
          # Clone the approved code repo (Repo 2) using the PAT for authentication
          git clone https://$REPO2_PAT@github.com/PawarSavitha/approved-code-repo.git Final-Logic-app-code

          # Copy the files (exclude .git and other unwanted files)
          cp -r * Final-Logic-app-code/

          cd Final-Logic-app-code

          # Set the user name and email for commit
          git config user.name "PawarSavitha"
          git config user.email "savithapawar038@gmail.com"

          # Add, commit, and push the changes to Repository 2
          git add .
          git commit -m "Approved logic app code"
          git push origin main
