name: Sync Logic App Workflows

on:
  push:
    branches:
      - main  # Trigger only when there's a push to the main branch
    paths:
      - 'workflows/**'  # Watch changes in the workflows director

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the source repository (Repo 1)
      - name: Checkout Source Repository (Repo 1)
        uses: actions/checkout@v3

      # Step 2: List all changed files
      - name: Identify Changed Files
        id: changed-files
        run: |
          changed_files=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $changed_files"
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      # Step 3: Clone the second repository (Repo 2)
      - name: Clone Target Repository (Repo 2)
        env:
          REPO2_PAT: ${{ secrets.REPO2_PAT }}
        run: |
          git clone https://$REPO2_PAT@github.com/PawarSavitha/Final-Logic-app-code.git PawarSavitha/code-approve

      # Step 4: Copy changed files to the Deploy directory in Repo 2
      - name: Copy Changed Files to Repo 2
        run: |
          cd PawarSavitha/code-approve
          mkdir -p Deploy
          for file in ${{ env.changed_files }}; do
            if [[ $file == workflows/* ]]; then
              echo "Copying $file to Deploy directory"
              cp ../$file Deploy/
            else
              echo "Skipping unrelated file: $file"
            fi
          done
          ls -R Deploy || echo "Deploy directory is empty"

      # Step 5: Commit changes to Repo 2 if any
      - name: Commit and Push Changes
        env:
          REPO2_PAT: ${{ secrets.REPO2_PAT }}
        run: |
          cd PawarSavitha/code-approve
          git config user.name "PawarSavitha"
          git config user.email "savithapawar038@gmail.com"
          git add .
          git status
          git diff --cached --exit-code || git commit -m "Sync updated workflows"
          git push origin main
