name: Push Modified File to Approved Code Repo

on:
  push:
    branches:
      - main

jobs:
  push-modified-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 1 (Logicapp-workflow)
        uses: actions/checkout@v3  # Checkout Repo 1 (Logicapp-workflow)

      - name: Identify modified files
        id: get_changed_files
        run: |
          # Check if this is the initial commit (first commit)
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "Initial commit detected. Listing all files."
            changed_files=$(git ls-files)
          else
            echo "Listing modified files from the latest commit."
            changed_files=$(git diff --name-only HEAD^..HEAD)
          fi
          echo "Changed files: $changed_files"
          echo "::set-output name=changed_files::$changed_files"

      - name: Debug Changed Files
        run: |
          echo "Changed files: ${{ steps.get_changed_files.outputs.changed_files }}"

      - name: Clone Repo 2 (Final-Logic-app-code)
        env:
          REPO2_PAT: ${{ secrets.REPO2_PAT }}
        run: |
          # Clone Repo 2 (Final-Logic-app-code) into workspace
          git clone https://$REPO2_PAT@github.com/PawarSavitha/app-code.git PawarSavitha/Final-Logic-app-code

      - name: Create Deploy Directory in Repo 2 (if not exists)
        run: |
          # Check if 'Deploy' directory exists, if not, create it
          mkdir -p Final-Logic-app-code/Deploy

      - name: Copy modified files to Repo 2
        run: |
          changed_files="${{ steps.get_changed_files.outputs.changed_files }}"
          if [ -n "$changed_files" ]; then
            for file in $changed_files; do
              if [[ $file == Logicapp-workflow/workflows/* ]]; then
                # Copy modified file from Repo 1 to Repo 2's Deploy directory
                cp $file Final-Logic-app-code/Deploy/
              fi
            done
          fi

      - name: Commit and Push Changes to Repo 2
        run: |
          cd Final-Logic-app-code
          git config user.name "PawarSavitha"
          git config user.email "savithapawar038@gmail.com"
          git add .
          git diff --cached --exit-code || git commit -m "Add modified files"
          git push origin main
