name: Push Modified File to Approved Code Repo

on:
  push:
    branches:
      - main

jobs:
  push-modified-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 1 (Source Repo)
        uses: actions/checkout@v3  # Ensure this uses the correct action

      - name: Identify Modified Files
        id: get_changed_files
        run: |
          # Get the list of modified files in the latest commit
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "Initial commit detected. Listing all files."
            changed_files=$(git ls-files)
          else
            echo "Listing modified files from the latest commit."
            changed_files=$(git diff --name-only HEAD^..HEAD)
          fi
          echo "Changed files: $changed_files"
          echo "::set-output name=changed_files::$changed_files"

      - name: Debug Changed Files
        run: |
          echo "Changed files: ${{ steps.get_changed_files.outputs.changed_files }}"

      - name: Clone Approved Code Repository (Repo 2)
        env:
          REPO2_PAT: ${{ secrets.REPO2_PAT }}  # Personal Access Token for Repo 2
        run: |
          # Clone Repo 2 into a temporary directory
          git clone https://github.com/PawarSavitha/Logicapp-workflow.git PawarSavitha/Final-Logic-app-code

      - name: Create Deploy Directory in Repo 2 (if it doesn't exist)
        run: |
          # Check if Deploy directory exists, if not create it
          mkdir -p Final-Logic-app-code/Deploy

      - name: Copy Modified Files to Repo 2's Deploy Directory
        run: |
          changed_files="${{ steps.get_changed_files.outputs.changed_files }}"
          if [ -n "$changed_files" ]; then
            for file in $changed_files; do
              # Only copy files from Logicapp-workflow/workflows/
              if [[ $file == Logicapp-workflow/workflows/* ]]; then
                echo "Copying $file to Repo 2's Deploy directory"
                cp $file Final-Logic-app-code/Deploy/
              fi
            done
          fi

      - name: Commit and Push Changes to Repo 2
        run: |
          cd Final-Logic-app-code
          git config user.name "PawarSavitha"
          git config user.email "savithapawar038@gmail.com"
          git add .  # Add all the copied files
          git diff --cached --exit-code || git commit -m "Add modified files"
          git push origin main
