name: Push Modified File to Approved Code Repo

on:
  push:
    branches:
      - main

jobs:
  push-modified-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 1
        uses: actions/checkout@v3

      - name: Identify modified files
        id: get_changed_files
        run: |
          # Check if this is the initial commit
          if [ $(git rev-list --count HEAD) -eq 1 ]; then
            echo "Initial commit detected. Listing all files."
            changed_files=$(git ls-files)
          else
            echo "Listing modified files from the latest commit."
            changed_files=$(git diff --name-only HEAD^..HEAD)
          fi
          echo "Changed files: $changed_files"
          echo "::set-output name=changed_files::$changed_files"

      - name: Debug Changed Files
        run: |
          echo "Changed files: ${{ steps.get_changed_files.outputs.changed_files }}"

      - name: Clone Approved Code Repository
        env:
          REPO2_PAT: ${{ secrets.REPO2_PAT }}
