name: Push Modified File to Approved Code Repo

on:
  push:
    branches:
      - main
    paths:
      - 'Logicapp-workflow/workflows/**' 

jobs:
  push-modified-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 1
        uses: actions/checkout@v3
        with:
          repository: PawarSavitha/Logicapp-workflow   # Replace with your actual repository name
          ref: main

      - name: Identify modified files
        id: get_changed_files
        run: |
          # Check if there are any previous commits to compare (for the first commit or when there is no history)
          if git rev-parse --verify HEAD^1 > /dev/null 2>&1; then
            # Get the list of modified files in the latest commit
            changed_files=$(git diff --name-only HEAD^..HEAD)
          else
            # If no previous commits, assume the current files are the new files
            changed_files=$(git ls-files)
          fi
          echo "Changed files: $changed_files"
          echo "::set-output name=changed_files::$changed_files"

      - name: Clone Approved Code Repository (which is empty initially)
        env:
          REPO2_PAT: ${{ secrets.REPO2_PAT }}
        run: |
          # Clone the empty repository (Repository 2)
          git clone https://$REPO2_PAT@github.com/PawarSavitha/Final-Logic-app-code.git Final-Logic-app-code

      - name: Copy modified files to Repo 2
        run: |
          # Copy only the modified file(s) to the target repo
          changed_files="${{ steps.get_changed_files.outputs.changed_files }}"
          if [ -n "$changed_files" ]; then
            for file in $changed_files; do
              cp $file Final-Logic-app-code/
            done
          fi

      - name: Commit and Push Changes to Repo 2
        run: |
          cd Final-Logic-app-code
          git config user.name "PawarSavitha"
          git config user.email "savithapawar038@gmail.com"

          git add .
          git commit -m "Approved logic app code"
          git push origin main
