name: Sync Logic App Workflows

on:
  push:
    branches:
      - main  # Trigger only when there's a push to the main branch
    paths:
      - 'workflows/**'  # Watch changes in the workflows director

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the first repository (Logicapp-workflow)
      uses: actions/checkout@v3
      with:
        repository: PawarSavitha/Logicapp-workflow
        token: ${{ secrets.REPO1_PAT }}
        
    - name: Detect changed files
      run: |
        echo "Checking for changes..."
        if git rev-parse HEAD^ >/dev/null 2>&1; then
          echo "Not the initial commit"
          changed_files=$(git diff --name-only HEAD^ HEAD)
        else
          echo "Initial commit detected"
          changed_files=$(git ls-files)
        fi
        echo "Changed files: $changed_files"
        echo "changed_files=$changed_files" >> $GITHUB_ENV
        
    - name: Clone the second repository (code-approve)
      run: |
        git clone https://$REPO2_PAT@github.com/PawarSavitha/code-approve.git PawarSavitha/code-approve
        
    - name: Debug - List the contents of the second repo
      run: |
        echo "Listing the contents of the repository:"
        ls -R PawarSavitha/code-approve

    - name: Copy the changed files to the second repository
      run: |
        if [ -n "$changed_files" ]; then
          for file in $changed_files; do
            # Ensure Deploy directory exists in Repo 2 before copying
            mkdir -p PawarSavitha/code-approve/Deploy
            cp "$file" PawarSavitha/code-approve/Deploy/
          done
        else
          echo "No files to copy"
        fi
        
    - name: Debug - Check the contents of the Deploy directory
      run: |
        echo "Contents of the Deploy directory in the second repo:"
        ls -R PawarSavitha/code-approve/Deploy/

    - name: Check git status in the second repository
      run: |
        cd PawarSavitha/code-approve
        git status
        
    - name: Commit and push changes to the second repository
      run: |
        cd PawarSavitha/code-approve
        git add .
        git commit -m "Add modified files"
        git push https://$REPO2_PAT@github.com/PawarSavitha/code-approve.git
        
    - name: Debug - Check commit log in the second repository
      run: |
        cd PawarSavitha/code-approve
        git log --oneline

    - name: Final check - List files in the second repo
      run: |
        cd PawarSavitha/code-approve
        echo "Final check: Listing files in the second repo"
        ls -R PawarSavitha/code-approve
