name: Sync Logic App Workflows

on:
  push:
    branches:
      - main  # Trigger only when there's a push to the main branch
    paths:
      - 'workflows/**'  # Watch changes in the workflows director

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the current repository (Logicapp-workflow)
    - name: Checkout LogicApp Workflow Repository
      uses: actions/checkout@v3
      with:
        repository: PawarSavitha/Logicapp-workflow

    # Step 2: Clone the code-approve repository
    - name: Clone the code-approve Repository
      env:
       REPO2_PAT: ${{ secrets.REPO2_PAT }}  # Ensure the PAT secret is set in the repo's secrets
      run: |
        git clone https://$REPO2_PAT@github.com/PawarSavitha/code-approve.git PawarSavitha/code-approve
        cd PawarSavitha/code-approve
        git remote set-url origin https://github.com/PawarSavitha/code-approve.git

    # Step 3: Copy the modified files to the Deploy directory in the code-approve repo
    - name: Copy Files to the code-approve Repository
      run: |
        echo "Listing changed files to be copied: $changed_files"
        if [ -n "$changed_files" ]; then
          for file in $changed_files; do
            # Ensure Deploy directory exists in Repo 2 before copying
            echo "Copying file: $file"
            mkdir -p PawarSavitha/code-approve/Deploy
            cp "$file" PawarSavitha/code-approve/Deploy/
          done
        else
          echo "No files to copy"
        fi

    # Step 4: Commit and Push Changes to code-approve Repository
    - name: Commit and Push Changes to code-approve Repository
      run: |
        cd PawarSavitha/code-approve
        git config user.name "PawarSavitha"
        git config user.email "savithapawar038@gmail.com"
        git add .
        git diff --cached --exit-code || git commit -m "Add modified files"
        git push https://$REPO2_PAT@github.com/PawarSavitha/code-approve.git main
