name: Push Modified File to Approved Code Repo

on:
  push:
    branches:
      - main

jobs:
  push-modified-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 1
        uses: actions/checkout@v3

      - name: Debug Directory Structure
        run: |
          echo "Current Directory Structure:"
          find .

      - name: Identify modified files
        id: get_changed_files
        run: |
          changed_files=$(git diff --name-only HEAD^..HEAD)
          echo "Changed files: $changed_files"
          echo "::set-output name=changed_files::$changed_files"

      - name: Debug Changed Files
        run: |
          echo "Changed files: ${{ steps.get_changed_files.outputs.changed_files }}"

      - name: Clone Approved Code Repository
        env:
          REPO2_PAT: ${{ secrets.REPO2_PAT }}
        run: |
          git clone https://$REPO2_PAT@github.com/PawarSavitha/approved-code-repo.git Final-Logic-app-code

      - name: Copy modified files to Repo 2
        run: |
          changed_files="${{ steps.get_changed_files.outputs.changed_files }}"
          if [ -n "$changed_files" ]; then
            for file in $changed_files; do
              if [[ $file == Logicapp-workflow/workflows/* ]]; then
                cp $file Final-Logic-app-code/
              fi
            done
          fi

      - name: Commit and Push Changes to Repo 2
        run: |
          cd Final-Logic-app-code
          git config user.name "PawarSavitha"
          git config user.email "savithapawar038@gmail.com"
          git add .
          git diff --cached --exit-code || git commit -m "Add modified files"
          git push origin main
